# Generated by Django 4.2 on 2023-12-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_terminal_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Terminal',
        ),
    ]
