# Generated by Django 4.2 on 2023-12-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_delete_bus_delete_terminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Kelaasor Flight'},
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='N0',
            new_name='No',
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ariport_1', to='flights.airport'),
            preserve_default=False,
        ),
    ]
