# Generated by Django 4.2 on 2023-12-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_alter_flight_options_rename_n0_airport_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(help_text='In rial'),
        ),
    ]
