# Generated by Django 4.2 on 2023-12-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='N0',
        ),
    ]
