# Generated by Django 4.2 on 2023-12-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_remove_bus_origin_remove_terminal_n0'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.terminal'),
            preserve_default=False,
        ),
    ]
