# Generated by Django 4.2 on 2023-12-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_remove_bus_origin_bus_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='destination',
            new_name='origin',
        ),
    ]
