# Generated by Django 4.2 on 2023-12-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_rename_destination_bus_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Kelaasor Bus'},
        ),
    ]
